# Generated by Django 5.0.14 on 2025-10-16 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='lectures.lecture'),
        ),
    ]
